### ISSUE TITLE
Form Name Rotation?

### ISSUE THREAD

**Issue by philipbjorge** [bion/superdelegation#29]
So I'm seeing form names like `field_B104BE44-176D-4CD9-9FDA-DBCBAEB5AAF9` everywhere.
Makes me think they might do field rotation over time to prevent spam? Thoughts?

**Comment by bion** [comment]
yeah we should keep an idea on failing message deliveries

On Thu, Mar 31, 2016 at 4:18 PM Philip Bjorge

<
mailto:Philip Bjorge <notifications@github.com>
> wrote:

So I'm seeing form names like

field_B104BE44-176D-4CD9-9FDA-DBCBAEB5AAF9

everywhere.

Makes me think they might do field rotation over time to prevent spam?

—

You are receiving this because you are subscribed to this thread.

Reply to this email directly or
https://github.com/bion/superdelegation/issues/29
https://github.com/bion/superdelegation/issues/29

**Comment by bion** [comment]
could also code them to not rely directly on the field names but find the fields based on their labels?

**Comment by bion** [comment]
@philipbjorge adapted this PR to find fields by associated label text instead of machine generated names: https://github.com/bion/superdelegation/pull/28/files

we should prefer that strategy whenever field names look generated
